const PostActionTypes = {
	POST_ERROR: 'POST_ERROR',
	GET_POST: 'GET_POST',
	GET_POSTS: 'GET_POSTS',
	UPDATE_LIKES: 'UPDATE_LIKES',
	DELETE_POST: 'DELETE_POST',
	ADD_POST: 'ADD_POST',
	ADD_COMMENT: 'ADD_COMMENT',
	DELETE_COMMENT: 'DELETE_COMMENT',
};

export default PostActionTypes;
