const ProfileActionTypes = {
	PROFILE_ERROR: 'PROFILE_ERROR',
	GET_PROFILE: 'GET_PROFILE',
	CLEAR_PROFILE: 'CLEAR_PROFILE',
	UPDATE_PROFILE: 'UPDATE_PROFILE',
	DELETE_ACCOUNT: 'DELETE_ACCOUNT',
	GET_ALL_PROFILES: 'GET_ALL_PROFILES',
	GET_REPOS: 'GET_REPOS',
};

export default ProfileActionTypes;
